version: '3'
services:
  php:
    image: php:7.0-apache
    restart: always
    volumes:
      - "./www:/var/www/html"
    ports:
      - "8000:80"

  db:
    image: mysql:5.7.10
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: mydb
        MYSQL_USER: root
        MYSQL_PASSWORD: root

  phpmyadmin:
   image: phpmyadmin/phpmyadmin
   links:
    - db:mysql
   ports:
     - 9191:80
   environment:
    PMA_HOST: mysql
